name: Release Project

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.1.1
    - run: gradle clean shadowJar
    - name: Attach JAR to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: build/libs/${{ matrix.artifact_name }}
